app1/urls.py
from app1.views import *
from django.urls import path

app_name='clientfirst'
urlpatterns=[
    path('client/',client,name='client'),
]

app2/urls.py
from app2.views import *
from django.urls import path

app_name='secondserver'

urlpatterns=[
    path('server/',server,name='server'),
]

project13/urls.py
from django.contrib import admin
from django.urls import path, include
import app1,app2
urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def client(request):
    return render(request,'client.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def server(request):
    return render(request,'server.html')

templates/client.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>Hey I'm Client! I need a Service ???</h1>
        <h2>Is it Available</h2>
        <h2><a href="{% url 'secondserver:server' %}">Response</a></h2>
    </center>
</body>
</html>

templates/server.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Hey I'm Server! How can I help you !!</h1>
    <h2><a href="{% url 'clientfirst:client' %}">Return</a></h2>
</body>
</html>